### ISSUE TITLE
All accounts trying to log in are kicked.

### ISSUE THREAD

**Issue by BEMZ01** [ad1tya2/AdiAuth#2] opened 2021-09-05 07:37 UTC
When I try to join the network with the plugin enabled, the following shows regardless of if the player is cracked or premium "please change your username to somthing uncommon, this username is already taken by a premium player".

Tested with my premium account, a the altening account and a cracked account all show the same message. 

EDIT: Console does not show anything, and client log does not show anything either.

**Comment by ad1tya2** [comment] 2021-09-05 08:52
This is only supposed to happen when you connect with a cracked account with a premium name,
But I have observed, if you cancel a connection while using a premium account by clicking on the cancel button and then reconnect then it shows this message,
Could you try connecting multiple times with a premium account and let me know the result?

**Comment by BEMZ01** [comment] 2021-09-05 08:55
Connections to the server take a while to process, but eventually I either timeout or the same error shows.

**Comment by ad1tya2** [comment] 2021-09-05 08:55
While using a premium account?

**Comment by ad1tya2** [comment] 2021-09-05 08:56
Can you send me the list of plugins on your bungeecord?

**Comment by ad1tya2** [comment] 2021-09-05 08:58
It definitely shouldn't timeout though 
🤔

**Comment by BEMZ01** [comment] 2021-09-05 08:58
yes while using a premium account.

Plugins list:
ViveCraft Extensions
ViaVersion
ViaRewind
ViaBackwords
UltraStaffChat
TAB
slingshot
ServerlistPlus
Plan
nuvotifyer
luckperms
HubCommand
Geyser
Floodgate
Craftingstore

Very quick responses 👍

**Comment by ad1tya2** [comment] 2021-09-05 09:02
Could you try Testing without any plugins?

**Comment by BEMZ01** [comment] 2021-09-05 09:03
also if it helps, a bit ago, waterfall was messing up, so i ran the hub server disconnected from the network and ran it in offline mode. i tried to remove my second data, but i feel it has persisted.

I'll try now :)

**Comment by ad1tya2** [comment] 2021-09-05 09:04
It seems like what is happening is that something is timing out your connection from which the server thinks that you are actually a cracked player with a premium name, and then disconnects you on the next login

**Comment by BEMZ01** [comment] 2021-09-05 09:10
just downloaded a fresh version of AdiAuth and Waterfall and Paper, Issue still persists with only AdiAuth installed

**Comment by ad1tya2** [comment] 2021-09-05 09:13
Ok so  is the backend server and it's in offline mode as well as the proxy?
And also, could you check if it times out without adiauth installed

**Comment by ad1tya2** [comment] 2021-09-05 09:15
Also btw download adiauth from spigot, I haven't updated the one on github to the latest commit 😅

**Comment by BEMZ01** [comment] 2021-09-05 09:31
i have downloaded from spigot
this might sound dumb, but i didnt realise that you needed to have it installed on the backend as well, ill test now and apologise if it works lol

**Comment by BEMZ01** [comment] 2021-09-05 09:41
Nope, im still timing out the first time, then second connection i get the error. The paper server log does not register a connection at all.

I did remove the plugin and managed to connect to the server without a hitch.

**Comment by ad1tya2** [comment] 2021-09-05 09:49
This is with a fully functional premium account?
If so try logging into hypixel and check,
 Also try logging in with a cracked account with the name xyz726hhj or  something random like that.

I can't really figure out how the hell this is happening XD, it worked perfectly for my server, sorry for the inconvenience but it's a new plugin so I hope you understand

**Comment by BEMZ01** [comment] 2021-09-05 12:27
its ok, i have programmed my own java plugin and I program in python I understand how hard it is to bug fix. I think this is just a "but it works on my machine moment".

I can join Hypixel and play a couple games of bedwars, join mineplex. my IGN is BEMZgames.

ill try a cracked account to join the server now

**Comment by BEMZ01** [comment] 2021-09-05 12:39
Cracked accounts time out 100% of the time No error other than "Timed out"

**Comment by ad1tya2** [comment] 2021-09-05 15:55
Maybe mojang api has blocked u or something?

**Comment by ad1tya2** [comment] 2021-09-05 17:15
1. Are you running bungeecord in offline mode?
2. Is something blocking adiauth from accessing the mojang api?
3. Could you try using plain bungeecord once?
4. Please share your adiauth config if possible

**Comment by ad1tya2** [comment] 2021-09-06 12:20
I think I might have the issue , could you try using 1.2 version and check?, That might fix the issue

**Comment by qSox** [comment] 2021-09-06 13:12
There is a problem when you are in the lobby and you want to connect to the main server, it throws you out for a reason "you are already connected to this server/proxy" is there a way to fix it ?

**Comment by ad1tya2** [comment] 2021-09-06 14:02
Download the latest build from spigot mc, that should fix it @qSox

**Comment by qSox** [comment] 2021-09-06 15:02
The same problem arises !!!

**Comment by ad1tya2** [comment] 2021-09-06 15:25
Uhh, I guess you will have to wait, I am sorry, I am travelling rn, a week at least before I can get access to a pc and good internet

**Comment by qSox** [comment] 2021-09-07 10:25
Well, what kind of plugin to put as a replacement and when it's okay to put yours. Because I don't want people to register again and I don't have time to wait ?

**Comment by ad1tya2** [comment] 2021-09-07 10:40
Try to do one thing, on the main GitHub page of this repo, you will see a green tick near the latest commit message, click on that and download the latest artifact and try to run that, that should fix your issue

**Comment by ad1tya2** [comment] 2021-09-07 10:43
Try to  download 1.3b1 from GitHub and check @qSox

**Comment by qSox** [comment] 2021-09-07 10:57
So far it works, if there are any other problems I will write .

**Comment by qSox** [comment] 2021-09-08 16:45
I found a bug that needs to be fixed, so when it's not a premium it says that there is such a person already in the server and it enters for the first time and there is not even a date base for it to be seen and fixed.

**Comment by BEMZ01** [comment] 2021-09-08 17:10
1. Are you running bungeecord in offline mode?
   - No (backend are as required by BungeeCord)

2. Is something blocking adiauth from accessing the mojang api?
   - Not that I know of

3. Could you try using plain bungeecord once?
   - Plan BungeeCord connects and logs in correctly.
   
4. Please share your adiauth config if possible
   - [Here ](https://pastebin.com/kP2gvWyt)(https://pastebin.com/kP2gvWyt)

**Comment by ad1tya2** [comment] 2021-09-08 22:20
@qSox could you explain your issue in more detail? Also make another issue

**Comment by ad1tya2** [comment] 2021-09-08 22:29
@BEMZ01 try to use [b2 in releases](https://github.com/ad1tya2/AdiAuth/releases/tag/1.3b2) and check

**Comment by qSox** [comment] 2021-09-09 06:56
@ad1tya2 The server is put into a test version and it happens so that there is only staff in which 3 we have a premium 3 do not have when trying to one of the guys to enter the server with no premium it turns out that such a name already exists and must change any that first does not exist reason because for the first time it enters the server if it changes, however, the nickname is done, so I write when it is released, there are a lot of people if this happens at 10 or 15 or I don't even know how often this glitch can happen, and almost everyone has a big problem for non-premium people

**Comment by ad1tya2** [comment] 2021-09-09 09:24
@qSox your issue is unrelated and is just causing clutter. Please create a new one when you decide to reply again. 
Right now the plugin works in this way, if you are a cracked player and you are using a nickname that is used by a premium account you can't play.
You will need to change your nickname to something that is not taken by a premium player to play, maybe I will change this in the future but it's ok for now

**Comment by qSox** [comment] 2021-09-09 09:36
I understand well how it work plugin but the question is that there is no person with a premium in this name and it turns out that I have to change nickname?
There is no logic to change the name if it is the only one with such a name on the server

**Comment by ad1tya2** [comment] 2021-09-09 10:10
I don't mean to be rude, but what part of create a new issue do you not understand?

**Comment by ad1tya2** [comment] 2021-09-17 08:57
@BEMZ01 i am unable to reproduce your issue

**Comment by ad1tya2** [comment] 2021-09-23 15:28
Closing issue because i am unable to reproduce this.

**Closed as completed by ad1tya2** 2021-09-23 15:28 UTC
Labels: bug
