### ISSUE TITLE
Error occurred while contacting login server, are they down?

### ISSUE THREAD

**Issue by dabucz** [ad1tya2/AdiAuth#4] opened 2022-01-24 10:00 UTC
When i try to login to my server it sends big error to console

10:08:23 [SEVERE] java.lang.NoSuchFieldException: uniqueId
10:08:23 [SEVERE] [AdiAuth] Login unsuccessful!
10:08:23 [SEVERE]     at java.lang.Class.getDeclaredField(Class.java:2070)
10:08:23 [SEVERE]     at ad1tya2.adiauth.Bungee.events.Handler.onLogin(Handler.java:80)
10:08:23 [SEVERE]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:08:23 [SEVERE]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:08:23 [SEVERE]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:08:23 [SEVERE]     at java.lang.reflect.Method.invoke(Method.java:498)
10:08:23 [SEVERE]     at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
10:08:23 [SEVERE]     at net.md_5.bungee.event.EventBus.post(EventBus.java:49)
10:08:23 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412)
10:08:23 [SEVERE]     at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:553)
10:08:23 [SEVERE]     at net.md_5.bungee.connection.InitialHandler.access$800(InitialHandler.java:72)
10:08:23 [SEVERE]     at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:448)
10:08:23 [SEVERE]     at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:436)
10:08:23 [SEVERE]     at net.md_5.bungee.http.HttpHandler.done(HttpHandler.java:68)
10:08:23 [SEVERE]     at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:59)
10:08:23 [SEVERE]     at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:14)
10:08:23 [SEVERE]     at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
10:08:23 [SEVERE]     at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
10:08:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
10:08:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
10:08:23 [SEVERE]     at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
10:08:23 [SEVERE]     at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
10:08:23 [SEVERE]     at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
10:08:23 [SEVERE]     at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
10:08:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
10:08:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
10:08:23 [SEVERE]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
10:08:23 [SEVERE]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
10:08:23 [SEVERE]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
10:08:23 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
10:08:23 [SEVERE]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
10:08:23 [SEVERE]     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
10:08:23 [SEVERE]     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
10:08:23 [SEVERE]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
10:08:23 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
10:08:23 [SEVERE]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
10:08:23 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
10:08:23 [SEVERE] Error authenticating Iusevapev with minecraft.net
java.lang.NullPointerException
    at net.md_5.bungee.chat.ComponentSerializer.toString(ComponentSerializer.java:74)
    at net.md_5.bungee.connection.InitialHandler.disconnect(InitialHandler.java:579)
    at net.md_5.bungee.connection.InitialHandler$6.done(InitialHandler.java:508)
    at net.md_5.bungee.connection.InitialHandler$6.done(InitialHandler.java:502)
    at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:40)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:413)
    at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:553)
    at net.md_5.bungee.connection.InitialHandler.access$800(InitialHandler.java:72)
    at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:448)
    at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:436)
    at net.md_5.bungee.http.HttpHandler.done(HttpHandler.java:68)
    at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:59)
    at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:14)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

**Comment by ad1tya2** [comment] 2022-01-24 18:01
Issue caused by another plugin, resolved via private message

**Closed as completed by ad1tya2** 2022-01-24 18:01 UTC
